[tool.poetry]
name = "consensus"
version = "0.1.0"
description = "Large Language Model Consensus Library (Mixture of Experts at Implementation level)"
authors = ["Frederik Bode <fbth@cs.aau.dk>"]
license = "GNU General Public License v3.0"
readme = "README.md"
homepage = "https://github.com/bodeby/consensus"
repository = "https://github.com/bodeby/consensus"
documentation = "https://new_project_name.readthedocs.io"


[tool.poetry.dependencies]
python = "^3.12"
transformers = "^4.42.3"
torch = "^2.3.1"
mkdocs-material = "^9.5.28"


[tool.poetry.group.dev.dependencies]
huggingface-hub = "^0.23.4"
pytest = "^8.2.2"
coverage = "^7.5.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
